query Members {
    members {
        name
        position
        designation
        bio
        linkedin
        twitter
        email       
        image {
            url
        }
    }
}